#-------------------------------
# General Site Settings
title: Edel Margherita Beckman
logo: logo.svg # You can add own logo.
description: Edel Margherita Beckman's personal website


#-------------------------------
# Author Settings
author:
  name: Edel Margherita Beckman
  image: 01.jpg
  say-hello: Hello, I’m <strong>Edel</strong>
  bio: <strong>Criminologist</strong> and <strong>Consultant</strong>, focused on <strong>NCII</strong> (Stop Non-Consensual Intimate Image Abuse), I'm working with public and private institutions to fostering a culture of kindness and equality.


#-------------------------------
# Contact links
instagram: https://instagram.com/edel_beckman # Add your Instagram handle
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: edel_beckman # Add instagram username


#-------------------------------
# Google Analytics
#google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
#mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
